### ISSUE TITLE
Enhancement Request: Possibility of customising the reactions

### ISSUE THREAD

**Issue by suhasa010** [YouTwitFace/ChannelHashBot#2]
Hi Andrew,

Thanks for the super useful bot.
Just wanted to see if there's a possibility of customising the reactions to the post. Like we could add our own emojis instead of the default 👍👎 emojis.

Regards,
Suhasa

**Comment by vrumger** [comment]
Telegram has reactions now and I've removed the option to enable likes, so this is no longer necessary.
